<a href="https://colab.research.google.com/github/A01703130/Extraccion_de_datos/blob/main/Act1_1Extracci%C3%B3n_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
#Convertir en dataframe
df= pd.read_excel("Detalle precios y productos fabricados 2022.xlsx")
df

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [34]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   datetime64[ns]
 2   NOMBRE_VENDEDOR            1424 non-null   object
 3   NOMBRE_CLIENTE             1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   float64
 8   COSTO_UNITARIO             1426 non-null   float64
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   float64
 10  SUBTOTAL_PARTIDA           1426 non-null   float64
 11  COSTO_TOTAL_CALCULADO      1426 non-null   float64
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   float64
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 156.1+ KB

In [35]:
#Imprimo los primeros 5 registro del dataframe
df.head()

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41

# **FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [38]:
#Se filtra dentro de Nombre_cliente, público en general
filtro1=df[df["NOMBRE_CLIENTE"] == "PÚBLICO EN GENERAL"]
filtro1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
57,F37134,2022-01-17,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,4,RB00010,BOB 8020 CAL.19 1612W 127V CER-8CANALES,605.00,44.70,44.70,2420.00,178.80,560.30,2241.20
69,F37153,2022-01-20,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00245,BAN P COMUN 100CMX21MM 900W220V T/TOR,522.00,51.38,51.38,1044.00,102.76,470.62,941.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1371,F39748,2022-12-09,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,TUE00206,"TUB INOX 5/16""Øx930mm 1000W 127V CAPUCHO",576.65,0.00,366.62,1153.30,733.23,210.03,420.07
1375,F39752,2022-12-13,AARON NUÑO CORDOVA,PÚBLICO EN GENERAL,1,TU5/16X870J127V,"TUB INOX 5/16""ØX800MM 2000W127V ""J"" TBOY",689.63,227.18,227.18,689.63,227.18,462.44,462.44
1376,F39754,2022-12-13,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,4,CS14D2017B20,"CAS INOX 1/4""ØX2"" 175W240V EXT30CM C/TJ",3416.00,222.14,222.14,6832.00,444.27,3193.86,6387.73
1392,F39780,2022-12-16,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TP0012,"TERMOPAR CERAMICO T/ K"" LONG 12"" CAL.14""",410.00,57.60,57.60,410.00,57.60,352.40,352.40
1410,F39817,2022-12-22,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,TP0016,"TERMOPAR CERAMICO T/K"" LONG 24"" CAL 8""",732.00,0.00,317.50,1464.00,635.00,414.50,829.00

In [39]:
filtro1.to_csv("Filtro_por_objeto.csv")
#descargar archivo filtrado en csv
from google.colab import files   
files.download("Filtro_por_objeto.csv")

In [40]:
#Filtro por filas
#Se están filtrando las filas 6,20 y 100
filtro2=df.iloc[ [6, 20, 100] , : ]  #Filas no consecutivas 
filtro2

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
20,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,3,WRE-4885,BAN INOX 36MMØX25MM 150W 240V EXT30CM,496.35,27.43,27.43,1489.05,82.29,468.92,1406.76
100,F37223,2022-01-28,LETICIA RAMIREZ HERNANDEZ,COMPONENTES ELECTRICOS Y DISPOSITIVOS ESPECIALES,1,TP0025,"TERMOPAR K 3/16Ø X 1' 1/2 EXT. 2 MT""",175.00,75.89,75.89,175.00,75.89,99.11,99.11

In [41]:
filtro2.to_csv("filtro_por_filas.csv")
from google.colab import files   
files.download("filtro_por_filas.csv")

In [42]:
#Filtro por columnas
#Se están filtrando las primeras 4 columnas
filtro3=df.iloc[ : , 1:4]       #Columnas consecutivas 
filtro3

      FECHA_DOC            NOMBRE_VENDEDOR                NOMBRE_CLIENTE
0    2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL
1    2022-01-05  LETICIA RAMIREZ HERNANDEZ  JUAN ANTONIO RESENDIZ UGALDE
2    2022-01-05   DIEGO ARMANDO LEON DURAN     ANA BARBARA CRUZ PALACIOS
3    2022-01-05   DIEGO ARMANDO LEON DURAN          OMAR RODRIGUEZ GOMEZ
4    2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL
...         ...                        ...                           ...
1421 2022-12-23  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ
1422 2022-12-23  LETICIA RAMIREZ HERNANDEZ     LUIS ENRIQUE PATIÑO PEREZ
1423 2022-12-23  LETICIA RAMIREZ HERNANDEZ          SEVEN DAYS ALL SPORT
1424 2022-12-23  LETICIA RAMIREZ HERNANDEZ           REVUELTA MONTECARLO
1425 2022-12-23         AARON NUÑO CORDOVA                CPEG SOLUTIONS

[1426 rows x 3 columns]

In [43]:
filtro3.to_csv("filtro_por_columnas.csv")
from google.colab import files   
files.download("filtro_por_columnas.csv")

In [47]:
#Filtro de filas vs columnas 
#Se filtran filas y columnas por nombre del cliente y fecha que se indica posteriormente
df1= pd.read_excel("Detalle precios y productos fabricados 2022.xlsx", index_col=1)
df1

,CVE_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
FECHA_DOC,,,,,,,,,,,,,
2022-01-05,F37034,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
2022-01-05,F37036,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2022-01-05,F37041,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
2022-01-05,F37042,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
2022-01-05,F37043,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,F39834,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
2022-12-23,F39834,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
2022-12-23,F39835,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
2022-12-23,F39837,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
2022-12-23,F39838,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [48]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
#Aqui se observa como filtre por la fechas del documento y por el nombre del cliente 
filtro4=df1.loc[["2022-01-05","2022-12-23"], ["NOMBRE_CLIENTE"]]
filtro4

                                 NOMBRE_CLIENTE
FECHA_DOC
2022-01-05                   PÚBLICO EN GENERAL
2022-01-05         JUAN ANTONIO RESENDIZ UGALDE
2022-01-05            ANA BARBARA CRUZ PALACIOS
2022-01-05                 OMAR RODRIGUEZ GOMEZ
2022-01-05                   PÚBLICO EN GENERAL
2022-01-05                   PÚBLICO EN GENERAL
2022-01-05  AIRBUS HELICOPTERS MEXICO QUERETARO
2022-01-05            ANA BARBARA CRUZ PALACIOS
2022-01-05                   FIDEICOMISO F/1596
2022-01-05                   FIDEICOMISO F/1596
2022-01-05                   FIDEICOMISO F/1596
2022-01-05                   FIDEICOMISO F/1596
2022-01-05                   FIDEICOMISO F/1596
2022-01-05            SANDIBEEL BECERRA HURTADO
2022-01-05                      INDUSTRIAS NIBA
2022-01-05                   MOLINERA DE MEXICO
2022-01-05             SILCA CERAMICO PRODUCTOS
2022-01-05              OSCAR VALDEZ GUADARRAMA
2022-01-05                             ELICAMEX
2022-01-05                             ELICAMEX
2022-01-05                             ELICAMEX
2022-12-23                            MEGO AFEK
2022-12-23                       CPEG SOLUTIONS
2022-12-23           JUAN GERARDO GUZMAN FLORES
2022-12-23                               TORJJS
2022-12-23                               TORJJS
2022-12-23                      TRILOGIQ-MEXICO
2022-12-23                      TRILOGIQ-MEXICO
2022-12-23                      TRILOGIQ-MEXICO
2022-12-23                      TRILOGIQ-MEXICO
2022-12-23            LUIS ENRIQUE PATIÑO PEREZ
2022-12-23            LUIS ENRIQUE PATIÑO PEREZ
2022-12-23                 SEVEN DAYS ALL SPORT
2022-12-23                  REVUELTA MONTECARLO
2022-12-23                       CPEG SOLUTIONS

In [49]:
filtro4.to_csv("filtro_filasvs_columnas.csv")
#descargar archivo filtrado en csv
from google.colab import files   
files.download("filtro_filasvs_columnas.csv")

In [16]:
#Se muestran los primeros 10 registros
filtro5=df.head(10)
filtro5

,CVE_DOC,FECHA_DOC,NOMBRE,NOMBRE.1,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",$434.48,$52.80,$52.80,$434.48,$52.80,$381.68,$381.68
1,F37036,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT","$1,264.05",$327.18,$327.18,"$1,264.05",$327.18,$936.87,$936.87
2,F37041,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,$551.61,$177.68,$177.68,"$3,861.29","$1,243.73",$373.94,"$2,617.56"
3,F37042,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,$140,$38.96,$38.96,$140,$38.96,$101.04,$101.04
4,F37043,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,$172.41,$101.71,$101.71,$344.83,$203.42,$70.71,$141.41
5,F37043,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,$237.07,$49.41,$49.41,$474.14,$98.82,$187.66,$375.32
6,F37044,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,"$14,000","$5,323.76","$5,323.76","$14,000","$5,323.76","$8,676.24","$8,676.24"
7,F37046,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,$94.50,$38.96,$38.96,$283.50,$116.88,$55.54,$166.62
8,F37048,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA","$1,615",$517.89,$517.89,"$1,615",$517.89,"$1,097.11","$1,097.11"
9,F37049,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA","$1,615",$517.89,$517.89,"$1,615",$517.89,"$1,097.11","$1,097.11"

In [50]:
filtro5.to_csv("filtro_por_cabecera.csv")
from google.colab import files   
files.download("filtro_por_cabecera.csv")

In [51]:
#Filtro por comparacion
#Aqui se filtran  los costos que mayores a 100 
filtro6=df[df["COSTO_UNITARIO_CALCULADO"] > 100]
filtro6

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1420,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,PT00079,PT-100 7.5MMØX95MM EXT.48CM 3H C/MACHO,1177.07,477.16,477.16,2354.14,954.32,699.91,1399.82
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49

In [52]:
filtro6.to_csv("filtro_por_comparacion.csv")
from google.colab import files   
files.download("filtro_por_comparacion.csv")

In [57]:
#Filtro Y
#Aquí se filtran los costos unitarios  mayores a 100 y la fecha igual a 1 de mayo del 2022
filtro7=df[(df["COSTO_UNITARIO_CALCULADO"] < 100) & (df["FECHA_DOC"] == "2022-01-05")]
filtro7

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
13,F37053,2022-01-05,DIEGO ARMANDO LEON DURAN,SANDIBEEL BECERRA HURTADO,1,BO00051,BOB 8020 CAL.26 127V BAS28.5CMX27CM MICA,1485.25,0.00,86.22,1485.25,86.22,1399.03,1399.03
18,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,5,WRE-2133,BAN MICA 120mmØx50mm 850W 440V TTORNILLO,821.30,0.00,78.70,4106.50,393.48,742.60,3713.02
19,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,7,WRE-2774,BAN MICA Ø120MM X 50 MM 700W 440V T TOR,821.30,0.00,75.77,5749.10,530.41,745.53,5218.69
20,F37061,2022-01-05,ALFREDO CANELA,ELICAMEX,3,WRE-4885,BAN INOX 36MMØX25MM 150W 240V EXT30CM,496.35,27.43,27.43,1489.05,82.29,468.92,1406.76

In [59]:
filtro7.to_csv("filtro_y.csv")
from google.colab import files   
files.download("filtro_y.csv")

In [60]:
#Filtro o
#Aquí se filtran los costos unitarios mayores a 100 o la fecha igual a 1 de mayo del 2022
filtro8=df[(df["COSTO_UNITARIO_CALCULADO"] < 100) | (df["FECHA_DOC"] == "2022-01-05")]
filtro8

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408,F39815,2022-12-22,ALFREDO CANELA,START SERVICE,1,RP00231,REPARACION DE MAQUINA,2300.00,0.00,99.68,2300.00,99.68,2200.32,2200.32
1413,F39826,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,5,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1897.27,78.09,78.09,9486.35,390.43,1819.18,9095.92
1414,F39828,2022-12-23,LETICIA RAMIREZ HERNANDEZ,JUAN GERARDO GUZMAN FLORES,3,TP00018,"TIRA INOX 38MMX6"" 150W 127V T/TIPO H",510.00,51.16,51.16,1530.00,153.49,458.84,1376.51
1417,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BL00002,BL INOX 60mmØx50mm 400W 120/240V EXT30CM,925.82,65.31,65.31,1851.64,130.63,860.51,1721.01
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [61]:
filtro8.to_csv("filtro_O.csv")
from google.colab import files   
files.download("filtro_O.csv")

In [62]:
#Filtro not
#Aquí se filtran los costos unitarios menores o iguales  a 100 no la fecha igual a 1 de mayo del 2022
filtro9=df[~(df["COSTO_UNITARIO_CALCULADO"] >= 100) & ~(df["FECHA_DOC"] == "2022-01-05")]
filtro9

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
24,F37069,2022-01-07,AARON NUÑO CORDOVA,ADVANEX DE MEXICO,2,RP00150,REPARACION DE TERMOPAR,1500.00,0.36,0.36,3000.00,0.72,1499.64,2999.28
27,F37073,2022-01-07,LETICIA RAMIREZ HERNANDEZ,KARINA AGUILAR TORRES,6,TP0012,"TERMOPAR CERAMICO T/ K"" LONG 12"" CAL.14""",375.00,44.14,44.14,2250.00,264.83,330.86,1985.17
33,F37092,2022-01-11,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,10,PJ31A1F1A400,"TER J 3/16""ØX1"" EXT.2MTS MALLA Z/ESPADA",150.50,68.95,68.95,1505.00,689.45,81.56,815.55
34,F37092,2022-01-11,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,10,PK31A1F1A400,"TER K 3/16""ØX1"" EXT.2MT RES/MALLA INOX",215.96,78.32,78.32,2159.60,783.24,137.64,1376.36
35,F37095,2022-01-11,DIEGO ARMANDO LEON DURAN,JOSE LUIS VARELA CORONA,1,RP00172,REPARACION DE SELLADORA PCS-300,382.10,5.76,5.76,382.10,5.76,376.34,376.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408,F39815,2022-12-22,ALFREDO CANELA,START SERVICE,1,RP00231,REPARACION DE MAQUINA,2300.00,0.00,99.68,2300.00,99.68,2200.32,2200.32
1413,F39826,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,5,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1897.27,78.09,78.09,9486.35,390.43,1819.18,9095.92
1414,F39828,2022-12-23,LETICIA RAMIREZ HERNANDEZ,JUAN GERARDO GUZMAN FLORES,3,TP00018,"TIRA INOX 38MMX6"" 150W 127V T/TIPO H",510.00,51.16,51.16,1530.00,153.49,458.84,1376.51
1417,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BL00002,BL INOX 60mmØx50mm 400W 120/240V EXT30CM,925.82,65.31,65.31,1851.64,130.63,860.51,1721.01
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [63]:
filtro9.to_csv("filtro_not.csv")
from google.colab import files   
files.download("filtro_not.csv")